### ISSUE TITLE
Intermittent error when containers first start

### ISSUE THREAD

**Issue by jrhea** [ConsenSys/qbc#4]
3 times out of 10 I see an error when running this command:
```
$ make stop && make test
```
Error message:
> Fatal: Unable to attach to remote geth: dial unix /var/qdata/dd/geth.ipc: connect: connection refused

Note: in the cases where it fails....the blocknumber seems to stall out

**Comment by jrhea** [comment]
Run this script to see if it is happening on other machines

```
#!/bin/bash

for i in {1..10}; do
  echo "TEST ${i}"
  make stop &> /dev/null;
  make test
done
```

**Comment by atoulme** [comment]
This hasn't happened in a while so closing.
