### ISSUE TITLE
Latest tag on Docker Hub missing

### ISSUE THREAD

**Issue by Magicking** [ConsenSys/qbc#52]
The only available tag on Docker Hub is `0.3` (https://hub.docker.com/r/consensys/quorum/tags/) where some examples mention `latest` tag instead.

**Comment by atoulme** [comment]
We don't push `latest`, and it looks like we should. I'll fix. Thanks!

**Comment by atoulme** [comment]
This is fixed with release 0.4. Thank you for your report!

**Comment by Magicking** [comment]
As a second thought, `latest` should exist or is it not ready yet?
