### ISSUE TITLE
Add websocket support

### ISSUE THREAD

**Issue by Magicking** [ConsenSys/qbc#53]
Related to #44, WebSocket is required to properly support pub/sub RPC

**Comment by atoulme** [comment]
We added the ports, but didn't open them in the docker compose examples. I can add those if that helps, unless there's something else that needs to be addressed?

**Comment by atoulme** [comment]
OK good to know. Will fix ASAP.

**Comment by atoulme** [comment]
Fix merged. Please reopen if there's more to it!
